"""Add temp_password column to User

Revision ID: e7ef04ea234a
Revises: c3f039ae1897
Create Date: 2025-12-26 06:30:18.431485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ef04ea234a'
down_revision: Union[str, Sequence[str], None] = 'c3f039ae1897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_password')
    # ### end Alembic commands ###
